name: Scala CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [11, 17, 21, 23]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: sbt

      - name: Setup scala
        uses: sbt/setup-sbt@v1

      - name: Build
        run: sbt clean compile

      - name: Test (1)
        if: ${{ matrix.os != 'macos-latest' }}
        run: sbt 'test -- --exclude-tag macos'

      - name: Test (2) - only MacOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: sbt test