name: Meet Every Thursday
on:
  # Instead of running on commits, this will run on a schedule
  schedule:
    # Uses POSIX cron syntax to define the schedule
    # For more details, see: https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#schedule
    - cron: '00 17 * * 4' # At 17:00 every Thursday (UTC)


jobs:
  # Defines a job to create a GitHub issue
  create_issue:
    name: Create team sync issue
    runs-on: ubuntu-latest 
    permissions:
      issues: write # Grants permission to create and manage issues
    steps:
      # Step 1: Create the issue using the Github CLI
      - name: Create team sync issue
        run: | 
          if [[ $CLOSE_PREVIOUS == true ]]; then
            previous_issue_number=$(gh issue list \
              --label "$LABELS" \
              --json number \
              --jq '.[0].number')
            if [[ -n $previous_issue_number ]]; then
              gh issue close "$previous_issue_number"
              gh issue unpin "$previous_issue_number"
            fi
          fi
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --assignee "$ASSIGNEES" \
            --label "$LABELS" \
            --body "$BODY")
          if [[ $PINNED == true ]]; then
            gh issue pin "$new_issue_url"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: Team sync
          ASSIGNEES: amordahl
          LABELS: weekly sync,docs-team
          BODY: |
            ### Agenda

            - [ ] Start the recording
            - [ ] Check-ins
            - [ ] Discussion points
            - [ ] Post the recording

            ### Discussion Points
            Add things to discuss below

            - [Work this week](https://github.com/orgs/github/projects/3)
          PINNED: false
          CLOSE_PREVIOUS: false

